### PR TITLE
Remove jimaku.cc listing

### PR DESCRIPTION
**Pull request by Rapptz**
Hi.

I'm the creator of this resource, shown [here](https://github.com/Rapptz/jimaku). I'd like to formally request my resource be removed from here. I don't really appreciate the warning being shown here because I have an optional, non-mandatory, link to a Discord server in case someone wants to talk to me and other people.

The accusation of saying I'm promoting spyware is overly harsh, *especially* since the server itself is free software under AGPL-v3 and is the only one that is FOSS, yet it's the only resource here tainted with a warning. I have no plan to remove the Discord link, nor do I force anyone to join it. Currently some things require contact but it can be done via email (`support@jimaku.cc`) instead of Discord but in the future the two remaining things that involve a human component (i.e. reporting and deleting accounts) will just be implemented within the site in due time.

Since I'd rather not put any more thought into this, please remove the listing instead.

### CODE REVIEW

**Comment by tatsumoto-ren** [comment]
Hello👋. Thanks for reaching out. 

When, for example, you open the [F-Droid](https://f-droid.org) app, you sometimes see that it tells you about anti-features in some apps, right? We do something similar, so I don't think it's *harsh*. 

Example:

screenshot

We just need to inform our readers before they find this resource elsewhere. If people learn about jimaku from some random place, they might get hurt. Plus, if we mention something, we think it can be helpful for language learners despite the downsides.

>I don't really appreciate the warning being shown 

There's indeed some concerns that have been raised regarding the website in question. Namely, that it promotes non-free network services and includes non-free JavaScript code. So that's what we've had to mention on our site. But the JS being nonfree could be a mistake, it appears that it you forgot to include a license.

screenshot 1

screenshot 2

Since you say that the javascript code on your site is free, please consider adding a license [as described here](https://www.gnu.org/software/librejs/free-your-javascript.html).

> I have an optional, non-mandatory, link to a Discord server in case someone wants to talk to me and other people.

Discord is a [proprietary surveillance engine](https://stallman.org/discord.html). I think it is important to warn the users about the risks associated with running discord. Could you please add such a warning on the website? If you do so, you can edit this PR and simply remove the warning that we have placed on our site.

Alternatively, you could set up a [bridge with matrix](https://matrix.org/ecosystem/bridges/discord/). This way people could talk to you on discord using their matrix accounts without being forced to run discord or have discord accounts. 

>Currently some things require contact but it can be done via email 

I'm not sure if the email address can be easily found on the site. Have you already removed it?

> I'd like to formally request my resource be removed from here.

The problem with doing so is that our readers would likely assume that it is not included because we forgot to do so. In such case, they will either ask us to add it, or they will use it without knowing about the potential downsides. When there's a resource that has a potential to provide value to language learners, and the resource has anti-features, there's always a tough decision. We could either be silent and don't mention it. In this case, people may learn about it elsewhere and accidentally get hurt. Or we could mention it and provide the necessary warnings to teach our readers about how to use the resource without being harmed. 

Recently other language learning webisites have been advertising jimaku, so I think it's better if our readers learn about it from us and get informed about the anti-features, than if they learn about it from a random website that doesn't bother correctly describing the available resources.

**Comment by tatsumoto-ren** [comment]
I have created a couple PRs to address the mentioned issues. The PRs are editable so feel free to change anything if you feel like it.

**Comment by Rapptz** [comment]
Hi.

> When, for example, you open the [F-Droid](https://f-droid.org/) app, you sometimes see that it tells you about anti-features in some apps, right? We do something similar, so I don't think it's harsh.

The harshness is the hypocrisy. This is the *only* resource in the entire page that has the warning despite there being countless of non-free resources and links there. You can make the argument that GitHub itself has some non-free spyware or that it has some negative issues such as supporting ICE. Then there's all the Mega links and external links with the same issue you give me (e.g. failing Libre-JS). My issue is that if you want to give me a warning then it should be applied in a fair metric, which it isn't. 

For example, just look at AnkiWeb:

image

Tae Kim's Guide:

image

Mega:

image

Element's Matrix client:

image

> There's indeed some concerns that have been raised regarding the website in question. Namely, that it promotes non-free network services and includes non-free JavaScript code. So that's what we've had to mention on our site. But the JS being nonfree could be a mistake, it appears that it you forgot to include a license.

All the JavaScript on the site is either AGPL or a permissive license such as MIT. There is no harm here, again it seems that the biggest sticking point is just the Discord link.

> Discord is a [proprietary surveillance engine](https://stallman.org/discord.html). I think it is important to warn the users about the risks associated with running discord. Could you please add such a warning on the website? If you do so, you can edit this PR and simply remove the warning that we have placed on our site.

I have no plans to warn users over this because again they are not forced to participate. I have no reason to warn them because it's within their own freedom to participate. The warning just aims to deter people from joining without giving them any sense of nuance. Which might be fine for you, since it isn't your community, but it isn't fine for me where I have a website to run and maintain.

> Alternatively, you could set up a [bridge with matrix](https://matrix.org/ecosystem/bridges/discord/). This way people could talk to you on discord using their matrix accounts without being forced to run discord or have discord accounts.

I mentioned in the other PR that I'd rather not do this. My experience with Matrix is rather poor -- every time I join I either run into some bugs or displeasing conversations, such as last time:

firefox_BDjLyIjlE2

> The problem with doing so is that our readers would likely assume that it is not included because we forgot to do so. In such case, they will either ask us to add it, or they will use it without knowing about the potential downsides. When there's a resource that has a potential to provide value to language learners, and the resource has anti-features, there's always a tough decision. We could either be silent and don't mention it. In this case, people may learn about it elsewhere and accidentally get hurt. Or we could mention it and provide the necessary warnings to teach our readers about how to use the resource without being harmed.

Again, if you want to do this please do it consistently. As it stands right now I'm being singled out. If you want to be pragmatic then feel free. Right now it just feels like a personal dislike against Discord has taken priority over the rest of the nits so you marked me down.

**Comment by tatsumoto-ren** [comment]
> The harshness is the hypocrisy. This is the only resource in the entire page that has the warning despite there being countless of non-free resources and links there. 

I'm gonna have to sort of disagree with you there. We try to report on anti-features in learning resources that we list on our website. For example, we have added some warnings next to itazuraneko, the old ajatt blog, Senmanga, Rawkuma, etc.

If there are any anti-features in other resources that we forgot to mention, please don't hesitate to either tell me about them or create a pull request that edits the corresponding parts of the guide.

However, we don't report on non-free javascript. If we did, we would have to mark virtually every single external link on Tatsumoto, and that's not very practical. This is unfortunate, but this is the world we live in. I only mentioned the JS issue in the comment here because it's something you can fix very easily.

> You can make the argument that GitHub itself has some non-free spyware or that it has some negative issues such as supporting ICE. 

Most of the time I interact with github is when I push from the command line. Or when I use the github cli. Github apparently does have a lot of problems, but it's not a language learning website, and language learners don't need it that much. 

I don't know what ICE is. What does it stand for, and why should I be concerned about it?

>Then there's all the Mega links and external links with the same issue you give me (e.g. failing Libre-JS). 

On our site we have a little button next to each Mega link telling you to download via [megatools](https://archlinux.org/packages/extra/x86_64/megatools/). megatools is free software. 

Other external links may fail the librejs checks as well, but that's not enough to state that they promote non-free network  services, which is the warning we've placed next to jimaku. Jimaku promotes Discord, a proprietary spyware program.

> My issue is that if you want to give me a warning then it should be applied in a fair metric, which it isn't.

I think it's fair. But since you've reached out to us, I am honored that you've done so, and I think we could help you fix the aforementioned issue very easily. I've expressed some of the options that you could take in https://github.com/Rapptz/jimaku/issues/8.


>For example, just look at AnkiWeb:

They don't have a *discord server*, but they use something called [Discourse](https://www.discourse.org/), which you can explore [here](https://forums.ankiweb.net/). Maybe it would be a good choice for you too. 

> Tae Kim's Guide
> Mega
> Element's Matrix client

No discord server either.

> All the JavaScript on the site is either AGPL or a permissive license such as MIT.

I'm very glad that this is the case. Now you can tag your JavaScript as free. I've proposed the required changes [here](https://github.com/Rapptz/jimaku/pull/9). I hope it helps.

> it seems that the biggest sticking point is just the Discord link.

Yes, I agree. We can't overlook that part.

> I have no plans to warn users over this because again they are not forced to participate.

Discord is mentioned 3 times in the API description, 6 times on the help page, and additionally once on every page of the site. Even if people are not required to join, they're clearly being pushed towards joining. That wouldn't be a problem if discord wasn't spyware, but since it is we'd appreciate it if there was some kind of warning. Or you could possibly make it less visible, less nagging. 

> I have no reason to warn them because it's within their own freedom to participate. The warning just aims to deter people from joining without giving them any sense of nuance. Which might be fine for you, since it isn't your community, but it isn't fine for me where I have a website to run and maintain.

It is made to look as if there's no other choice, and it's advertised quite heavily, so effectively it's almost mandatory for all actions on the site except searching and downloading.

We could help you with your community if you want. We could also merge your community and ours to make it even easier to maintain. 

> I mentioned in the other PR that I'd rather not do this. My experience with Matrix is rather poor -- every time I join I either run into some bugs or displeasing conversations, such as last time I registered on midov.pl to get access to the DJT channel since matrix.org users are "discouraged":

We recommend midov.pl for its reliability. You may not like the conversations in their official room, but you don't have to participate either. People who hang out in other rooms won't go out of their way to join your room, they won't even know that it exists unless you publish it. It's not the only server that we recommend. And you don't have to follow our recommendations when you set up your account. However, since it appears you already have an account, I think it's fine to continue using it.

matrix.org is fine, we just don't recommend it because our rooms are large and attract crypto spammers. for some reason all crypto spam comes from matrix.org. If you use matrix.org, I recommend not to publish your room in their directory.

> Again, if you want to do this please do it consistently. As it stands right now I'm being singled out. 

I hope I've demonstrated that we're trying to be consistent, and that you're not being singled out.

**Comment by Midek** [comment]
> 
> firefox_BDjLyIjlE2
> 

LOOK, MOM! IM ON THE TV!

**Comment by kanjieater** [comment]
Just a suggestion, but maybe the phrasing should be reworded to be consistent with the other resources.

In all the other resource listings, it's made explicit that the concern is Discord. Maybe simply advising your community to not click on the discord links like the other resources, would give people a clearer understanding of what your concern is, and would allow them to make an informed decision on the risks they want to undertake using others software / tools.

```
Don't click on any [Discord](https://spyware.neocities.org/articles/discord.html) links.
```
```
Includes links to [Discord](https://spyware.neocities.org/articles/discord.html) servers. Discord is known for spying on and politically suppressing its users.```

**Comment by brishtibheja** [comment]
@jonsmy Just curious, because you said "my website" in quotes, are people legally obligated in any country to do that? I mean if I talk about Joe's new website Joe just can't force me to stop referencing it right? I just felt using "my" appeals to some pretty archaic notions.

**Pull request merged**
